<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Student;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class RegistrationController extends Controller
{
    public function register(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'nisn' => 'required|string|max:20|unique:students,nisn',
            'name' => 'required|string|max:255',
            'class' => 'required|string|max:50',
            'username' => 'required|string|max:50|unique:users,username',
            'phone' => 'required|string|max:15|unique:users,phone',
            'email' => 'required|string|email|max:255|unique:users,email',
            'club_id' => 'required|exists:clubs,id',
            'password' => 'required|string|min:6',
            'confirm_password' => 'required|string|min:6|same:password',
        ]);

        if ($validator->fails()) {
            return response()->json([
                'message' => 'Validation failed',
                'errors' => $validator->errors(),
            ], 422);
        }

        $user = User::create([
            'name' => $request->name,
            'username' => $request->username,
            'email' => $request->email,
            'password' => bcrypt($request->password),
            'role' => 'student',
        ]);

        $student = Student::create([
            'user_id' => $user->id,
            'name' => $request->name,
            'nisn' => $request->nisn,
            'class' => $request->class,
            'phone' => $request->phone,
            'club_id' => $request->club_id,
        ]);

        return response()->json([
            'message' => 'Registration successful',
            'user' => $user,
        ], 201);
    }

    public function registerKetua(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'ekskul' => 'required',
            'grup_wa' => 'required|string|max:255',
            'nisn' => 'required|string|max:20|unique:students,nisn',
            'nama' => 'required|string|max:255',
            'username' => 'required|string|max:50|unique:users,username',
            'email' => 'required|string|email|max:255|unique:users,email',
            'tingkatan' => 'required|string|max:10',
            'jurusan' => 'required|string',
            'kelas' => 'required|string',
            'password' => 'required|string|min:6',
        ]);

        if ($validator->fails()) {
            return response()->json([
                'message' => 'Validation failed',
                'errors' => $validator->errors(),
            ], 422);
        }

        \Illuminate\Support\Facades\DB::beginTransaction();
        try {
            // Find or Create Jurusan
            // Check if jurusan is a hash_id/uuid
            $jurusanId = null;
            $jurusan = \App\Models\Jurusan::find($request->jurusan);
            if ($jurusan) {
                $jurusanId = $jurusan->id;
            } else {
                // Check if name already exists
                $jurusan = \App\Models\Jurusan::where('nama', $request->jurusan)->first();
                if (!$jurusan) {
                    $singkatan = collect(explode(' ', $request->jurusan))->map(function($w) { return strtoupper($w[0]); })->join('');
                    $jurusan = \App\Models\Jurusan::create([
                        'nama' => $request->jurusan,
                        'singkatan' => $singkatan,
                        // slug will be auto-generated by HasSlug if set up
                    ]);
                }
                $jurusanId = $jurusan->id;
            }

            // Find or Create Kelas
            $kelas = \App\Models\Kelas::where('nama', $request->kelas)->first();
            if (!$kelas) {
                // Format rombel from "X DKV 1", wait let's just save nama, tingkatan, jurusan_id
                $kelas = \App\Models\Kelas::create([
                    'nama' => $request->kelas,
                    'tingkatan' => $request->tingkatan,
                    'jurusan_id' => $jurusanId,
                ]);
            }

            // Find Club
            $club = \App\Models\Club::find($request->ekskul);
            if (!$club) {
                return response()->json(['message' => 'Ekskul tidak ditemukan', 'errors' => ['ekskul' => ['Ekskul tidak valid']]], 422);
            }

            // Create User (Role as club_pengurus)
            $user = User::create([
                'name' => $request->nama,
                'username' => $request->username,
                'email' => $request->email,
                'password' => bcrypt($request->password),
                'role' => 'club_pengurus',
            ]);

            // Create Student
            $student = Student::create([
                'user_id' => $user->id,
                'name' => $request->nama,
                'nisn' => $request->nisn,
                'kelas_id' => $kelas->id,
                'club_id' => $club->id,
            ]);

            // Update Club owner & WA link
            $club->update([
                'student_id' => $student->id,
                'group_link' => $request->grup_wa,
            ]);

            \Illuminate\Support\Facades\DB::commit();

            return response()->json([
                'message' => 'Pendaftaran Ketua Ekskul berhasil',
                'user' => $user,
            ], 201);
        } catch (\Exception $e) {
            \Illuminate\Support\Facades\DB::rollBack();
            \Illuminate\Support\Facades\Log::error("Register Ketua Error: " . $e->getMessage());
            return response()->json([
                'message' => 'Terjadi kesalahan pada server',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}
